### PR TITLE
Add Sync trait bound to error variants.

### PR DESCRIPTION
**Pull request by tmpfs**
I found that after upgrading to v3 and calling the `Entry` functions and converting to `anyhow::Result` caused a compiler error due to unsatisfied trait bounds:

```
error[E0277]: `(dyn StdError + std::marker::Send + 'static)` cannot be shared between threads safely
   --> rust/src/api/keyring.rs:37:57
    |
37  |             entry.set_password(password.expose_secret())?;
    |                                                         ^ `(dyn StdError + std::marker::Send + 'static)` cannot be shared between threads safely
    |
    = help: the trait `std::marker::Sync` is not implemented for `(dyn StdError + std::marker::Send + 'static)`, which is required by `Result<(), anyhow::Error>: FromResidual<Result<Infallible, keyring::Error>>`
    = help: the following other types implement trait `FromResidual<R>`:
              <Result<T, F> as FromResidual<Yeet<E>>>
              <Result<T, F> as FromResidual<Result<Infallible, E>>>
    = note: required for `Unique<(dyn StdError + std::marker::Send + 'static)>` to implement `std::marker::Sync`
note: required because it appears within the type `Box<(dyn StdError + std::marker::Send + 'static)>`
```

Adding the `Sync` trait bound to the error variants fixes this issue.

### CODE REVIEW

**Comment by brotskydotcom** [comment]
Thanks for this PR.  The removal of this marker was actually a workaround for a bug in one of the keystores.  I didn't realize that the removal would cause problems with the use of anyhow.  Let me work on fixing this down the chain.

**Comment by brotskydotcom** [comment]
Created bug #185 from this PR.

**Comment by brotskydotcom** [comment]
@tmpfs I've just release v3.0.1 - please see if this fixes the issue, thanks! -d.

**Comment by brotskydotcom** [comment]
Superseded by the release of 3.0.1.  Thanks for the bug report!
